# Generated by Django 4.2.5 on 2023-09-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0005_itemimage_remove_item_image_alter_item_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='item_images/'),
        ),
        migrations.AlterModelTable(
            name='itemimage',
            table=None,
        ),
    ]
