# Generated by Django 4.2.5 on 2023-09-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0006_remove_item_images_itemimage_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='images', to='e_commerce_app.item'),
        ),
        migrations.AlterModelTable(
            name='itemimage',
            table='item_image',
        ),
    ]
